### ISSUE TITLE
unable to issue cert on a modern cluster with modern cert-manager/k8s/something?

### ISSUE THREAD

**Issue by stephgosling** [4nx/cert-manager-webhook-joker#5]
hi.

Tried to follow the instructions to generate a cert but they're currently not working:

*environment*
*  kubernetes v1.24.4
*  provisioner: talos
*  cert-manager version: v1.10.1 installed via their helm instructions

steps to reproduce:

create'n'apply the secret:
```
cat 00-joker-creds.yaml 
apiVersion: v1
kind: Secret
metadata:
  name: joker-credentials
  namespace: kube-system
data:
  username: <username>
  password: <password>
```

add the role and role binding (n.b. indentation in the `README.md` is broken):

```
cat 01-joker.yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-joker:secret-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["joker-credentials"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-joker:secret-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-joker:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-joker
```

add cluster issuer (note the jumping to 03, coming back to 02 in a moment):

```
cat 03-cert-issuer.yaml 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-joker
spec:
  acme:
    email: steph@chuci.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-joker-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.chuci.org
          solverName: joker
          config:
            baseURL: https://svc.joker.com/nic/replace
            dnsType: TXT
            userNameSecretRef:
              name: joker-credentials
              key: username
            passwordSecretRef:
              name: joker-credentials
              key: password
```
attempt to issue cert:
```
cat 04-cert.yaml 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foo
spec:
  secretName: foo-secret
  commonName: foo.chuci.org
  dnsNames:
  - foo.chuci.org
  issuerRef:
    name: letsencrypt-joker
    kind: ClusterIssuer
```

The above fails like this:

```
Error presenting challenge: joker.acme.chuci.org is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "joker" in API group "acme.chuci.org" at the cluster scope
```
a day or so googling [finds this](https://stackoverflow.com/questions/73157331/k8s-unable-to-generate-lets-encrypt-certificates-for-godaddy-domains-using-cert) so write the following:

```
cat 02-clusterrole.yaml 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-challenge-missing-role
rules:
  - apiGroups: ["acme.chuci.org"]
    resources: ["joker"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-challenge-missing-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-challenge-missing-role
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
```
delete and recreate everything but still stuck:
```
k describe cert foo | tail -n 4
  ----    ------     ----  ----                                       -------
  Normal  Issuing    13m   cert-manager-certificates-trigger          Issuing certificate as Secret does not exist
  Normal  Generated  13m   cert-manager-certificates-key-manager      Stored new private key in temporary Secret resource "foo-ztk79"
  Normal  Requested  13m   cert-manager-certificates-request-manager  Created new CertificateRequest resource "foo-675kg"
```
```
   k describe certificaterequest foo-675kg | tail -n 4 
  Type    Reason           Age   From                                          Message
  ----    ------           ----  ----                                          -------
  Normal  cert-manager.io  13m   cert-manager-certificaterequests-approver     Certificate request has been approved by cert-manager.io
  Normal  OrderCreated     13m   cert-manager-certificaterequests-issuer-acme  Created Order resource default/foo-675kg-816627957
```
```
  k describe order foo-675kg-816627957 | tail -n 3
  Type    Reason   Age   From                 Message
  ----    ------   ----  ----                 -------
  Normal  Created  14m   cert-manager-orders  Created Challenge resource "foo-675kg-816627957-3913900244" for domain "foo.chuci.org"
  ```
```
   k describe challenge foo-675kg-816627957-3913900244 | tail -n 4
  Type     Reason        Age                  From                     Message
  ----     ------        ----                 ----                     -------
  Normal   Started       14m                  cert-manager-challenges  Challenge scheduled for processing
  Warning  PresentError  4m13s (x8 over 14m)  cert-manager-challenges  Error presenting challenge: the server could not find the requested resource (post joker.acme.chuci.org)
```

the -webhook-joker logs simply say this:

```
I1121 18:20:48.765289       1 shared_informer.go:197] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1121 18:20:48.765596       1 secure_serving.go:178] Serving securely on [::]:443
I1121 18:20:48.766096       1 dynamic_serving_content.go:129] Starting serving-cert::/tls/tls.crt::/tls/tls.key
I1121 18:20:48.766131       1 tlsconfig.go:219] Starting DynamicServingCertificateController
I1121 18:20:48.865246       1 shared_informer.go:204] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I1121 18:20:48.865590       1 shared_informer.go:204] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
I1121 18:20:50.516537       1 log.go:181] http: TLS handshake error from 10.244.0.0:14005: EOF
I1121 18:20:50.521569       1 log.go:181] http: TLS handshake error from 10.244.0.0:1189: read tcp 10.244.2.71:443->10.244.0.0:1189: read: connection reset by peer
I1121 18:20:50.521700       1 log.go:181] http: TLS handshake error from 10.244.0.0:39237: read tcp 10.244.2.71:443->10.244.0.0:39237: read: connection reset by peer
I1121 18:20:55.508642       1 log.go:181] http: TLS handshake error from 10.244.1.0:10458: EOF
```
ditto cert-manager:

```
I1121 22:40:13.142589       1 dns.go:88] cert-manager/challenges/Present "msg"="presenting DNS01 challenge for domain" "dnsName"="foo.chuci.org" "domain"="foo.chuci.org" "resource_kind"="Challenge" "resource_name"="foo-675kg-816627957-3913900244" "resource_namespace"="default" "resource_version"="v1" "type"="DNS-01"
E1121 22:40:13.149638       1 controller.go:167] cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="the server could not find the requested resource (post joker.acme.chuci.org)" "key"="default/foo-675kg-816627957-3913900244"
```

one or two other people have seen similar behaviour so I have cross-posted to [cert-manager](https://github.com/cert-manager/cert-manager/issues/5069) 

Given it affects other provider webhooks and given I needed to add a `ClusterRole` and `ClusterRoleBinding` to get this far, something likely changed.

This is a new cluster for me, so I'm curious which versions do you have running successfully so we can trace where a breaking change may be?
